In [1]:
import numpy as np
from numpy.linalg import norm

In [3]:
def randomization(n):
    """
    Arg:
      n - an integer
    Returns:
      A - a randomly-generated nx1 Numpy array.
    """
    
    A = np.random.randint(low = 0, high = n, size = 10)
    return A 

In [4]:
randomization(100)

array([89,  0, 57, 61, 60,  0, 70, 91, 55, 12])

In [8]:
def operations(h, w):
    """
    Takes two inputs, h and w, and makes two Numpy arrays A and B of size
    h x w, and returns A, B, and s, the sum of A and B.

    Arg:
      h - an integer describing the height of A and B
      w - an integer describing the width of A and B
    Returns (in this order):
      A - a randomly-generated h x w Numpy array.
      B - a randomly-generated h x w Numpy array.
      s - the sum of A and B.
    """
    
    A = np.random.randint(1,10,size=(h,w))
    B = np.random.randint(1,10,size=(h,w))
    s = A + B
    
    return print('A:\n', A, '\n\nB:\n', B, '\n\ns:\n', s, '\n')

In [10]:
operations(4, 3)

A:
 [[5 9 3]
 [6 4 8]
 [5 7 4]
 [3 5 7]] 

B:
 [[4 3 2]
 [7 2 9]
 [9 3 2]
 [5 5 6]] 

s:
 [[ 9 12  5]
 [13  6 17]
 [14 10  6]
 [ 8 10 13]] 



In [11]:
def norm(A, B):
    """
    Takes two Numpy column arrays, A and B, and returns the L2 norm of their
    sum.

    Arg:
      A - a Numpy array
      B - a Numpy array
    Returns:
      s - the L2 norm of A+B.
    """
  
    s = np.linalg.norm(A + B)
    return s

In [12]:
A = np.arange(10).reshape(10,1)
b = [5, 7, 1, 0, 8, 2, 9, 4, 3, 6]
B = np.array(b).reshape(10,1) 
norm(A,B)

31.496031496047245

In [20]:
def neural_network(inputs, weights):
    """
     Takes an input vector and runs it through a 1-layer neural network
     with a randomized weight matrix and one output.
     Arg:
       inputs - 2 x 1 NumPy array
       weights - 2 x 1 NumPy array
     Returns (in this order):
       out - a 1 x 1 NumPy array, representing the output of the neural network
    """
    z = np.tanh(weights.T.dot(inputs))
    
    return z

In [56]:
x=[1,0]
inputs = np.array(x).reshape(2,1)
y=[0.38,0.55]
weights = np.array(y).reshape(2,1)
neural_network(inputs, weights)

array([[0.36270747]])

In [58]:
def scalar_function(x, y):
    if x <= y:
        return x*y
    else:
        return x/y

In [59]:
scalar_function(5, 3)

1.6666666666666667

In [60]:
#if x and y are arrays
def scalar_function1(x, y):   
    xy = np.zeros( ( len(x), len(y) ) )
    for j in range(len( y )):
        for i in range(len( x )):           
            if (x[i] > y[j]):      
                xy[i,j] = x[i]/y[j]
            else: 
                xy[i,j] = x[i] * y[j]
    return xy

In [28]:
x = [1, 2, 3, 4, 5]
y = [5, 1, 3, 2, 4]
scalar_function1(x, y)

array([[ 5.        ,  1.        ,  3.        ,  2.        ,  4.        ],
       [10.        ,  2.        ,  6.        ,  4.        ,  8.        ],
       [15.        ,  3.        ,  9.        ,  1.5       , 12.        ],
       [20.        ,  4.        ,  1.33333333,  2.        , 16.        ],
       [25.        ,  5.        ,  1.66666667,  2.5       ,  1.25      ]])

In [50]:
def vector_function(x, y):
    """
    Make sure vector_function can deal with vector input x,y 
    """
    #Your code here
    v = np.vectorize(scalar_function)
    return v

In [51]:
vector_function(6, 2)